// Niche profiles. Jev picks one from the extracted fields; everything niche-specific (question wording,
// report examples, schema type) reads from here. Add a niche = add an entry.
export type Niche = {
  key: string; label: string; audience: string; // who the site is trying to win
  aiQuestion: string; // what that audience asks an AI assistant
  credentials: string; // what checkable standing looks like here
  schemaType: string; jobTitle: string;
  faq: [string, string, string];
  testimonialOutcome: string; // an example of a concrete outcome in a testimonial
};

export const NICHES: Record<string, Niche> = {
  education_consultant: { key: "education_consultant", label: "Education consultant", audience: "parents and students", aiQuestion: "who is a good college admissions consultant near me, and what do they cost", credentials: "an IECA, HECA, or NACAC membership, a former admissions or counseling role at a named institution, or a named degree", schemaType: "ProfessionalService", jobTitle: "Independent Educational Consultant", faq: ["How much does a college admissions consultant cost?", "When should we start working together?", "Do you work with families outside your area?"], testimonialOutcome: "accepted to Duke, finished all essays by October" },
  therapist_or_coach: { key: "therapist_or_coach", label: "Therapist / coach", audience: "clients seeking help", aiQuestion: "who is a good therapist or coach near me for my situation, and what does a session cost", credentials: "a license (LMFT, LCSW, PsyD), a certification (ICF), or a named training institute", schemaType: "ProfessionalService", jobTitle: "Therapist", faq: ["How much does a session cost and do you take insurance?", "How do I know if we are a good fit?", "Do you offer online sessions?"], testimonialOutcome: "back at work after six weeks, sleeping again" },
  legal: { key: "legal", label: "Law practice", audience: "potential clients", aiQuestion: "who is a good lawyer near me for this kind of case, and what do they charge", credentials: "bar admissions, board certifications, named case results, or a former role such as prosecutor or clerk", schemaType: "LegalService", jobTitle: "Attorney", faq: ["How much do you charge and is the first consultation free?", "What kinds of cases do you take?", "How long does a case like mine take?"], testimonialOutcome: "case dismissed, settlement in four months" },
  financial_advisor: { key: "financial_advisor", label: "Financial advisor / accountant", audience: "clients and households", aiQuestion: "who is a trustworthy financial advisor or CPA near me, and how do they charge", credentials: "CFP, CPA, CFA, fiduciary status, or a named firm affiliation", schemaType: "FinancialService", jobTitle: "Financial Advisor", faq: ["How are you paid — fees or commissions?", "Are you a fiduciary?", "Who do you typically work with?"], testimonialOutcome: "retired two years early, taxes down 30%" },
  home_services: { key: "home_services", label: "Home services (contractor, plumber, HVAC)", audience: "homeowners", aiQuestion: "who is a reliable licensed contractor or plumber near me, and what do they charge", credentials: "a license number, insurance, manufacturer certifications, or years in business", schemaType: "HomeAndConstructionBusiness", jobTitle: "Owner", faq: ["Are you licensed and insured?", "Do you give free estimates?", "What areas do you serve?"], testimonialOutcome: "fixed the same day, came in under the quote" },
  health_or_dental: { key: "health_or_dental", label: "Health / dental practice", audience: "patients", aiQuestion: "who is a good dentist or clinic near me that takes new patients, and what does it cost", credentials: "board certification, a medical or dental degree, hospital affiliations, or accepted insurance", schemaType: "MedicalBusiness", jobTitle: "Practitioner", faq: ["Are you accepting new patients?", "Which insurance do you accept?", "What should I expect at a first visit?"], testimonialOutcome: "pain gone after one visit, no wait" },
  real_estate: { key: "real_estate", label: "Real estate agent", audience: "buyers and sellers", aiQuestion: "who is a top real estate agent in my area, and what is their track record", credentials: "a brokerage license, sales volume, years in the market, or named designations", schemaType: "RealEstateAgent", jobTitle: "Real Estate Agent", faq: ["What is your commission?", "How long do your listings take to sell?", "Which neighborhoods do you cover?"], testimonialOutcome: "sold in nine days over asking" },
  agency_or_consultant: { key: "agency_or_consultant", label: "Agency / business consultant", audience: "business owners", aiQuestion: "who is a good agency or consultant for my kind of business, and what do they cost", credentials: "named client results, certifications, case studies with numbers, or press", schemaType: "ProfessionalService", jobTitle: "Founder", faq: ["What does an engagement cost?", "What results have you delivered for businesses like mine?", "How long until we see results?"], testimonialOutcome: "leads doubled in 90 days" },
  restaurant_or_hospitality: { key: "restaurant_or_hospitality", label: "Restaurant / hospitality", audience: "guests", aiQuestion: "what is a good place to eat or stay near me, and what does it cost", credentials: "awards, press, chef background, or years open", schemaType: "Restaurant", jobTitle: "Owner", faq: ["Do you take reservations?", "Do you have vegetarian or allergy-friendly options?", "What are your hours?"], testimonialOutcome: "best meal of the trip, table ready on time" },
  other_local_service: { key: "other_local_service", label: "Local service business", audience: "local customers", aiQuestion: "who is a good provider of this service near me, and what do they charge", credentials: "a license, certification, membership, or years in business", schemaType: "LocalBusiness", jobTitle: "Owner", faq: ["What do you charge?", "What areas do you serve?", "How quickly can you start?"], testimonialOutcome: "done on time, exactly as quoted" },
};
export const DEFAULT_NICHE = NICHES.education_consultant;
export const nicheOf = (key?: string) => NICHES[key ?? ""] ?? DEFAULT_NICHE;
