import type { Extraction, JevAnswer } from "./fields";
import { scoreSite, type Category, type Scored } from "./scoring";
import { nicheOf, type Niche } from "./niches";

// The free fix-it report: concrete actions derived from the extracted fields, each with the points it
// would add (simulated by applying the fix to a copy of the data and re-scoring — no AI involved).
export type Action = { category: Category; title: string; why: string; how: string; effort: "10 min" | "1 hour" | "half a day"; impact: 3 | 2 | 1; points: number; prerequisite?: boolean };
type State = { x: Extraction; a: Record<string, JevAnswer> };
type Fix = (s: State) => State;

const level = (a: Record<string, JevAnswer>, id: string, min: number): Record<string, JevAnswer> => {
  const cur = a[id]; if (cur?.type !== "score") return a;
  const top = Math.max(1, Object.keys(cur.legend).length - 1), score = Math.max(cur.score, Math.min(min, top));
  return { ...a, [id]: { ...cur, score, probabilities: { [String(Math.round(score))]: 1 }, confidence: 1 } };
};
const choose = (a: Record<string, JevAnswer>, id: string, key: string): Record<string, JevAnswer> => (a[id]?.type === "choice" ? { ...a, [id]: { type: "choice", choice: key, probabilities: { [key]: 1 }, confidence: 1 } } : a);
const yes = (a: Record<string, JevAnswer>, id: string): Record<string, JevAnswer> => ({ ...a, [id]: { type: "noul", noul: 0.95 } });

export function buildReport(x0: Extraction, a0: Record<string, JevAnswer>, host: string, shell?: boolean, nicheKey?: string): { actions: Action[]; now: Scored; after: Scored; niche: Niche } {
  const n = nicheOf(nicheKey);
  const defs: (Omit<Action, "points"> & { fix: Fix })[] = [];
  const add = (d: Omit<Action, "points"> & { fix: Fix }) => defs.push(d);
  const auth = a0.authority_positioning?.type === "choice" ? a0.authority_positioning.choice : "";
  const trustLevel = a0.trust_signal_quality?.type === "score" ? a0.trust_signal_quality.score : 0;
  const hasStrongSchema = x0.schema_types.some((s) => ["LocalBusiness", "ProfessionalService", "EducationalOrganization", "Service", n.schemaType].includes(s));

  if (shell) add({ category: "geo", impact: 3, effort: "half a day", prerequisite: true, title: "Make the site readable without JavaScript", why: "Your site sends crawlers an empty page and builds everything in the browser. Google can render it slowly; most AI assistants (ChatGPT, Perplexity, Claude) cannot, so to them your business does not exist. Every other fix depends on this one.", how: "Ask your developer for server-side rendering or static export (Next.js, Astro, or a Webflow/Squarespace rebuild). Test it: view-source on your homepage should show your actual text.", fix: (s) => s });
  if (!x0.has_faq_block) add({ category: "geo", impact: 3, effort: "1 hour", title: `Add a real FAQ with 6–10 questions ${n.audience} ask`, why: `Question-and-answer blocks are what AI assistants quote most. ${n.audience[0].toUpperCase() + n.audience.slice(1)} ask assistants things like "${n.aiQuestion}".`, how: `Add an FAQ on the homepage or a /faq page with headings that are the exact questions: "${n.faq[0]}", "${n.faq[1]}", "${n.faq[2]}". Answer each in 2–4 plain sentences with a number or a timeframe in it.`, fix: (s) => ({ x: { ...s.x, has_faq_block: true, schema_types: [...s.x.schema_types, "FAQPage"] }, a: level(s.a, "geo_readiness", 2) }) });
  if (!hasStrongSchema) add({ category: "geo", impact: 3, effort: "10 min", title: `Add ${n.schemaType} structured data`, why: "Structured data is the machine-readable label on your business: what you do, where, and for whom. Without it, assistants and search engines have to guess.", how: "Paste the JSON-LD snippet at the bottom of this report into your site's <head> (Squarespace: Settings → Advanced → Code Injection; Webflow: Page settings → Custom code; WordPress: a header-scripts plugin).", fix: (s) => ({ x: { ...s.x, schema_types: [...s.x.schema_types, n.schemaType, "Person"] }, a: level(s.a, "geo_readiness", 2) }) });
  else if (x0.has_faq_block && !x0.schema_types.includes("FAQPage")) add({ category: "geo", impact: 2, effort: "10 min", title: "Mark your FAQ up as FAQPage schema", why: "You have questions on the page; telling crawlers they are an FAQ makes them eligible to be quoted directly.", how: "Add FAQPage JSON-LD listing each question and answer (snippet below).", fix: (s) => ({ x: { ...s.x, schema_types: [...s.x.schema_types, "FAQPage"] }, a: level(s.a, "geo_readiness", 3) }) });

  if (!x0.meta_description.length) add({ category: "seo", impact: 3, effort: "10 min", title: "Write a meta description", why: "It is the summary search engines and AI assistants quote for your homepage. Right now they have nothing.", how: `One or two sentences, 120–160 characters: who you help, what you do, where you are, and one proof point.`, fix: (s) => ({ x: { ...s.x, meta_description: { text: "x".repeat(140), length: 140 } }, a: level(s.a, "geo_readiness", 1) }) });
  else if (x0.meta_description.length > 165 || x0.meta_description.length < 70) add({ category: "seo", impact: 1, effort: "10 min", title: `Trim the meta description to 120–160 characters (now ${x0.meta_description.length})`, why: "Search results cut it off; the end of your sentence disappears.", how: "Lead with the service and place; put credentials second.", fix: (s) => ({ ...s, x: { ...s.x, meta_description: { text: s.x.meta_description.text.slice(0, 140), length: 140 } } }) });
  if (!x0.meta_title.length) add({ category: "seo", impact: 3, effort: "10 min", title: "Add a page title", why: "The title is the headline of your search result.", how: "\"[Service] in [Town] | [Your Name]\" — 50–60 characters.", fix: (s) => ({ ...s, x: { ...s.x, meta_title: { text: "x".repeat(55), length: 55 } } }) });
  else if (x0.meta_title.length > 65 || x0.meta_title.length < 30) add({ category: "seo", impact: 1, effort: "10 min", title: `Resize the page title to 50–60 characters (now ${x0.meta_title.length})`, why: "Long titles are truncated in results; short ones waste the space.", how: "Pattern: service + place + name.", fix: (s) => ({ ...s, x: { ...s.x, meta_title: { text: s.x.meta_title.text.slice(0, 55), length: 55 } } }) });
  if (typeof x0.page_speed_score === "number" && x0.page_speed_score < 70) add({ category: "seo", impact: 2, effort: "1 hour", title: `Speed up mobile load (Google scores it ${x0.page_speed_score}/100)`, why: `${n.audience[0].toUpperCase() + n.audience.slice(1)} browse on phones. Slow pages lose visitors before they read a word, and speed is a ranking factor.`, how: "Compress hero images (under 200 KB), remove unused embeds and fonts, and turn on lazy loading. Re-test at pagespeed.web.dev.", fix: (s) => ({ ...s, x: { ...s.x, page_speed_score: 90 } }) });
  if (x0.mobile_friendly === false) add({ category: "seo", impact: 2, effort: "10 min", title: "Add a mobile viewport tag", why: "Without it the site does not scale to phones.", how: "Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> to the <head>.", fix: (s) => ({ ...s, x: { ...s.x, mobile_friendly: true } }) });

  if (!x0.testimonial_text_blocks.length) add({ category: "trust", impact: 3, effort: "1 hour", title: "Add 3–5 testimonials with outcomes", why: `${n.audience[0].toUpperCase() + n.audience.slice(1)} choose on other people's results. Jev found no testimonials on your homepage or About page.`, how: `Ask recent clients for two sentences each: the outcome ("${n.testimonialOutcome}") and what it was like to work with you. Use first name + last initial, or a role.`, fix: (s) => ({ x: { ...s.x, testimonial_text_blocks: ["a", "b", "c"] }, a: yes(level(s.a, "trust_signal_quality", 3), "discretion_respected") }) });
  else if (trustLevel < 1.5) add({ category: "trust", impact: 2, effort: "1 hour", title: "Make testimonials specific", why: "Jev rated your trust evidence as generic praise. \"Great service!\" is not believable; a named outcome is.", how: `Edit each testimonial to name a result ("${n.testimonialOutcome}") and attribute it to a person or role.`, fix: (s) => ({ ...s, a: level(s.a, "trust_signal_quality", 3) }) });
  if (a0.discretion_respected?.type === "noul" && x0.testimonial_text_blocks.length && a0.discretion_respected.noul < 0.6) add({ category: "trust", impact: 1, effort: "10 min", title: "Protect client privacy in testimonials", why: "Full names plus specifics identify people. Discretion is a selling point.", how: "Use first name + last initial, or a role.", fix: (s) => ({ ...s, a: yes(s.a, "discretion_respected") }) });
  if (!x0.credential_text_blocks.length) add({ category: "authority", impact: 3, effort: "10 min", title: "State your credentials on the homepage", why: "Jev found no credentials. People (and AI assistants) look for checkable standing.", how: `One line under your name: ${n.credentials}. Link each to where it can be verified.`, fix: (s) => ({ x: { ...s.x, credential_text_blocks: ["c"] }, a: choose(level(s.a, "trust_signal_quality", 2), "authority_positioning", "reads_as_recognized_authority") }) });
  if (auth === "reads_as_competent_but_generic") add({ category: "authority", impact: 2, effort: "10 min", title: "Replace generic claims with specific ones", why: "\"Experienced\" and \"personalized\" appear on every competitor's site. They are invisible.", how: `Swap each generic claim for a number or a name: years and clients served, ${n.credentials}.`, fix: (s) => ({ ...s, a: choose(s.a, "authority_positioning", "reads_as_recognized_authority") }) });
  if (auth === "reads_as_thin_or_unfinished") add({ category: "authority", impact: 3, effort: "1 hour", title: "Say who you are and what you do, above the fold", why: "The title, description and credentials together do not tell a reader what this business is.", how: "Headline: the service and who it is for. Subline: your name, credential, place. One sentence of proof.", fix: (s) => ({ x: { ...s.x, meta_title: { text: "x".repeat(55), length: 55 }, meta_description: { text: "x".repeat(140), length: 140 } }, a: choose(s.a, "authority_positioning", "reads_as_recognized_authority") }) });
  if (!x0.schema_types.some((s) => ["Person", "Organization", "ProfessionalService", "LocalBusiness", "EducationalOrganization", n.schemaType].includes(s)) && hasStrongSchema) add({ category: "authority", impact: 1, effort: "10 min", title: "Add Person schema for the founder", why: "It lets assistants connect the business to a named, credentialed person.", how: "Included in the JSON-LD snippet below.", fix: (s) => ({ ...s, x: { ...s.x, schema_types: [...s.x.schema_types, "Person"] } }) });

  if (!x0.google_business_profile_linked) add({ category: "discoverability", impact: 3, effort: "1 hour", title: "Claim and link a Google Business Profile", why: "It is the single biggest local-search signal, and where people read reviews. Jev found no link or map on your site.", how: "Create/claim the profile at business.google.com, collect 5+ reviews, then link \"Read our Google reviews\" from the homepage and footer.", fix: (s) => ({ ...s, x: { ...s.x, google_business_profile_linked: true } }) });
  if (x0.social_links_found.length < 3) add({ category: "discoverability", impact: 1, effort: "10 min", title: `Link your social profiles (found: ${x0.social_links_found.join(", ") || "none"})`, why: "Profile links corroborate that the business is real and active.", how: "Footer icons for LinkedIn, Instagram, Facebook or YouTube — whichever you actually post on.", fix: (s) => ({ ...s, x: { ...s.x, social_links_found: ["LinkedIn", "Instagram", "Facebook"] } }) });
  if (x0.word_count < 600) add({ category: "discoverability", impact: 2, effort: "half a day", title: `Add substance (${x0.word_count} words across two pages)`, why: "Thin pages give search engines and assistants nothing to match against real questions.", how: "A services page with pricing tiers, an About page with your story, and 3 short articles answering the questions in your FAQ.", fix: (s) => ({ ...s, x: { ...s.x, word_count: 1200 } }) });
  if (x0.last_modified_signal === "unknown") add({ category: "discoverability", impact: 1, effort: "10 min", title: "Show that the site is alive", why: "No last-updated signal. Stale-looking sites rank and convert worse.", how: "Add a dated post or an \"updated for 2026\" line, and keep it current.", fix: (s) => ({ ...s, x: { ...s.x, last_modified_signal: "2026-09-21" } }) });

  // Points: re-score with each fix applied alone; "after" applies all of them.
  const now = scoreSite(x0, a0);
  const actions: Action[] = defs.map(({ fix, ...d }) => ({ ...d, points: d.prerequisite ? 0 : Math.max(0, scoreSite(fix({ x: x0, a: a0 }).x, fix({ x: x0, a: a0 }).a).overall - now.overall) }));
  const all = defs.reduce<State>((s, d) => d.fix(s), { x: x0, a: a0 });
  const after = scoreSite(all.x, all.a);
  actions.sort((p, q) => (q.prerequisite ? 1 : 0) - (p.prerequisite ? 1 : 0) || q.points - p.points || q.impact - p.impact);
  return { actions, now, after, niche: n };
}

/** JSON-LD the site can paste in. Uses what we know; brackets mark what they fill in. */
export function jsonLd(host: string, x: Extraction, nicheKey?: string) {
  const n = nicheOf(nicheKey);
  const name = x.meta_title.text.split(/[|–—-]/)[0].trim() || host;
  const faqs = n.faq.map((q) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: "[Your answer in 2–4 sentences, with a number or timeframe.]" } }));
  return JSON.stringify({ "@context": "https://schema.org", "@graph": [
    { "@type": n.schemaType, "@id": `https://${host}/#business`, name, url: `https://${host}/`, description: x.meta_description.text || "[One-sentence description]", areaServed: "[City, State] and remote", address: { "@type": "PostalAddress", addressLocality: "[City]", addressRegion: "[State]", addressCountry: "US" }, founder: { "@id": `https://${host}/#founder` }, sameAs: ["[Google Business Profile URL]", "[LinkedIn URL]"] },
    { "@type": "Person", "@id": `https://${host}/#founder`, name: "[Founder name]", jobTitle: n.jobTitle, worksFor: { "@id": `https://${host}/#business` }, hasCredential: "[Licenses, memberships, degrees]" },
    { "@type": "FAQPage", mainEntity: faqs },
  ] }, null, 2);
}
