import type { Extraction, JevAnswer } from "./fields";
import type { Category } from "./scoring";

// The free fix-it report: concrete actions derived from the extracted fields, in priority order.
// Written for an education consultant who does not read code. No LLM involved; this is deterministic.
export type Action = { category: Category; title: string; why: string; how: string; effort: "10 min" | "1 hour" | "half a day"; impact: 3 | 2 | 1 };

export function buildReport(x: Extraction, answers: Record<string, JevAnswer>, host: string, shell?: boolean): Action[] {
  const a: Action[] = [];
  const push = (act: Action) => a.push(act);
  const auth = answers.authority_positioning?.type === "choice" ? answers.authority_positioning.choice : "";
  const trustLevel = answers.trust_signal_quality?.type === "score" ? answers.trust_signal_quality.score : 0;

  if (shell) push({ category: "geo", impact: 3, effort: "half a day", title: "Make the site readable without JavaScript", why: "Your site sends crawlers an empty page and builds everything in the browser. Google can render it slowly; most AI assistants (ChatGPT, Perplexity, Claude) cannot, so to them your practice does not exist.", how: "Ask your developer for server-side rendering or static export (Next.js, Astro, or a Webflow/Squarespace rebuild). Test it: view-source on your homepage should show your actual text." });
  if (!x.has_faq_block) push({ category: "geo", impact: 3, effort: "1 hour", title: "Add a real FAQ section with 6–10 parent questions", why: "Question-and-answer blocks are what AI assistants quote most. Parents ask assistants things like 'how much does a college consultant cost' and 'when should we start'.", how: `Add an FAQ on the homepage or a /faq page with headings that are the exact questions parents ask ("How much do you charge?", "When should we start?", "Do you work with families outside your area?"). Answer each in 2–4 plain sentences with a number or a timeframe in it.` });
  if (!x.schema_types.some((s) => ["LocalBusiness", "ProfessionalService", "EducationalOrganization", "Service"].includes(s))) push({ category: "geo", impact: 3, effort: "10 min", title: "Add ProfessionalService structured data", why: "Structured data is the machine-readable label on your business: what you do, where, and for whom. Without it, assistants and search engines have to guess.", how: `Paste the JSON-LD snippet at the bottom of this report into your site's <head> (Squarespace: Settings → Advanced → Code Injection; Webflow: Page settings → Custom code; WordPress: a header-scripts plugin).` });
  else if (x.has_faq_block && !x.schema_types.includes("FAQPage")) push({ category: "geo", impact: 2, effort: "10 min", title: "Mark your FAQ up as FAQPage schema", why: "You have questions on the page; telling crawlers they are an FAQ makes them eligible to be quoted directly.", how: "Add FAQPage JSON-LD listing each question and answer (snippet below)." });

  if (!x.meta_description.length) push({ category: "seo", impact: 3, effort: "10 min", title: "Write a meta description", why: "It is the summary search engines and AI assistants quote for your homepage. Right now they have nothing.", how: "One or two sentences, 120–160 characters: who you help, what you do, where you are, and one proof point. Example: \"Independent college admissions consultant in New Canaan, CT. Essay coaching and application strategy for families since 2014. Harvard M.Ed.\"" });
  else if (x.meta_description.length > 165 || x.meta_description.length < 70) push({ category: "seo", impact: 1, effort: "10 min", title: `Trim the meta description to 120–160 characters (now ${x.meta_description.length})`, why: "Search results cut it off; the end of your sentence disappears.", how: "Lead with the service and place; put credentials second." });
  if (!x.meta_title.length) push({ category: "seo", impact: 3, effort: "10 min", title: "Add a page title", why: "The title is the headline of your search result.", how: "\"College Admissions Consultant in [Town] | [Your Name]\" — 50–60 characters." });
  else if (x.meta_title.length > 65 || x.meta_title.length < 30) push({ category: "seo", impact: 1, effort: "10 min", title: `Resize the page title to 50–60 characters (now ${x.meta_title.length})`, why: "Long titles are truncated in results; short ones waste the space.", how: "Pattern: service + place + name." });
  if (typeof x.page_speed_score === "number" && x.page_speed_score < 70) push({ category: "seo", impact: 2, effort: "1 hour", title: `Speed up mobile load (Google scores it ${x.page_speed_score}/100)`, why: "Parents browse on phones. Slow pages lose visitors before they read a word, and speed is a ranking factor.", how: "Compress hero images (under 200 KB), remove unused embeds and fonts, and turn on lazy loading. Re-test at pagespeed.web.dev." });
  if (x.mobile_friendly === false) push({ category: "seo", impact: 2, effort: "10 min", title: "Add a mobile viewport tag", why: "Without it the site does not scale to phones.", how: "Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> to the <head>." });

  if (!x.testimonial_text_blocks.length) push({ category: "trust", impact: 3, effort: "1 hour", title: "Add 3–5 testimonials with outcomes", why: "Parents choose consultants on other parents' results. Jev found no testimonials on your homepage or About page.", how: "Ask recent families for two sentences each: the outcome (\"accepted to Duke\", \"finished all essays by October\") and what it was like to work with you. Use first name + last initial, or role (\"parent of a 2025 graduate\")." });
  else if (trustLevel < 1.5) push({ category: "trust", impact: 2, effort: "1 hour", title: "Make testimonials specific", why: "Jev rated your trust evidence as generic praise. \"Great service!\" is not believable; a named outcome is.", how: "Edit each testimonial to name a result (a school, a scholarship, a timeline) and attribute it to a person or role." });
  if (answers.discretion_respected?.type === "noul" && x.testimonial_text_blocks.length && answers.discretion_respected.noul < 0.6) push({ category: "trust", impact: 1, effort: "10 min", title: "Protect client privacy in testimonials", why: "Full names plus schools identify families. Discretion is a selling point in this industry.", how: "Use first name + last initial, or \"parent, son at Duke\"." });
  if (!x.credential_text_blocks.length) push({ category: "authority", impact: 3, effort: "10 min", title: "State your credentials on the homepage", why: "Jev found no credentials. Parents (and AI assistants) look for checkable standing.", how: "One line under your name: degrees, former admissions roles, and memberships — IECA, HECA, NACAC. Link the membership to your directory profile." });
  if (auth === "reads_as_competent_but_generic") push({ category: "authority", impact: 2, effort: "10 min", title: "Replace generic claims with specific ones", why: "\"Experienced\" and \"personalized\" appear on every consultant's site. They are invisible.", how: "Swap each generic claim for a number or a name: \"20,000 essays since 2014\", \"former admissions reader at X\", \"IECA professional member\"." });
  if (auth === "reads_as_thin_or_unfinished") push({ category: "authority", impact: 3, effort: "1 hour", title: "Say who you are and what you do, above the fold", why: "The title, description and credentials together do not tell a reader what this business is.", how: "Headline: the service and who it is for. Subline: your name, credential, place. One sentence of proof." });
  if (!x.schema_types.some((s) => ["Person", "Organization", "ProfessionalService", "LocalBusiness", "EducationalOrganization"].includes(s))) push({ category: "authority", impact: 1, effort: "10 min", title: "Add Person schema for the founder", why: "It lets assistants connect the practice to a named, credentialed person.", how: "Included in the JSON-LD snippet below." });

  if (!x.google_business_profile_linked) push({ category: "discoverability", impact: 3, effort: "1 hour", title: "Claim and link a Google Business Profile", why: "It is the single biggest local-search signal, and where parents read reviews. Jev found no link or map on your site.", how: "Create/claim the profile at business.google.com (category: Educational consultant), collect 5+ reviews, then link \"Read our Google reviews\" from the homepage and footer." });
  if (x.social_links_found.length < 2) push({ category: "discoverability", impact: 1, effort: "10 min", title: `Link your social profiles (found: ${x.social_links_found.join(", ") || "none"})`, why: "Profile links corroborate that the business is real and active.", how: "Footer icons for LinkedIn (you), Instagram (results, tips) and YouTube if you have one." });
  if (x.word_count < 600) push({ category: "discoverability", impact: 2, effort: "half a day", title: `Add substance (${x.word_count} words across two pages)`, why: "Thin pages give search engines and assistants nothing to match against parents' questions.", how: "A services page with pricing tiers, an About page with your story, and 3 short articles answering the questions in your FAQ." });
  if (x.last_modified_signal === "unknown") push({ category: "discoverability", impact: 1, effort: "10 min", title: "Show that the site is alive", why: "No last-updated signal. Stale-looking sites rank and convert worse.", how: "Add a dated post or a \"Results for the class of 2026\" line, and keep it current." });

  return a.sort((p, q) => q.impact - p.impact);
}

/** JSON-LD the site can paste in. Uses what we know; brackets mark what they fill in. */
export function jsonLd(host: string, x: Extraction) {
  const name = x.meta_title.text.split(/[|–—-]/)[0].trim() || host;
  const faqs = x.has_faq_block ? [] : [{ "@type": "Question", name: "How much does a college admissions consultant cost?", acceptedAnswer: { "@type": "Answer", text: "[Your pricing tiers, e.g. hourly and package rates.]" } }, { "@type": "Question", name: "When should we start working together?", acceptedAnswer: { "@type": "Answer", text: "[Your answer, e.g. spring of junior year; earlier for competitive lists.]" } }];
  return JSON.stringify({ "@context": "https://schema.org", "@graph": [
    { "@type": "ProfessionalService", "@id": `https://${host}/#business`, name, url: `https://${host}/`, description: x.meta_description.text || "[One-sentence description]", areaServed: "[City, State] and remote", address: { "@type": "PostalAddress", addressLocality: "[City]", addressRegion: "[State]", addressCountry: "US" }, founder: { "@id": `https://${host}/#founder` }, sameAs: ["[Google Business Profile URL]", "[LinkedIn URL]"] },
    { "@type": "Person", "@id": `https://${host}/#founder`, name: "[Founder name]", jobTitle: "Independent Educational Consultant", worksFor: { "@id": `https://${host}/#business` }, memberOf: [{ "@type": "Organization", name: "IECA" }], alumniOf: "[University]" },
    { "@type": "FAQPage", mainEntity: faqs.length ? faqs : "[List each FAQ question and answer]" },
  ] }, null, 2);
}
